version: '3.3'

services:
    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - "5000"
        networks:
            - mlflow
        command: mlflow server --backend-store-uri sqlite:///mlruns.db --host 0.0.0.0        

    nginx:
        restart: always
        build:
            context: .
            dockerfile: Nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "80:80"
        networks:
            - mlflow
        depends_on:
            - web

networks:
    mlflow:
        driver: bridge
