version: '3.2'
services:
  db:
      image: sql
      build:
          context: .
          dockerfile: Sqlite
      container_name: sqlite-db
      expose:
          - "5000"
  mlflow:
      container_name: sklearn-model
      image: flow
      build:
          context: .
          dockerfile: Mlflow
      expose:
          - "3000"
      networks:
        - mlflow

networks:
  mlflow:
    driver: bridge

